spring.application.name=PaymentService
spring.datasource.url=jdbc:mysql://localhost:3306/paymentservice
spring.datasource.username=paymentserviceuser
#spring.datasource.password=yourpassword

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
stripe.key=${STRIPE_KEY}
order.service.url=http://localhost:8086
server.port=8090
