spring.application.name=PaymentService
spring.datasource.url=jdbc:mysql://localhost:3306/paymentservice
spring.datasource.username=paymentserviceuser
#spring.datasource.password=yourpassword

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
stripe.key=${STRIPE_KEY}
stripe.webhook.secret= whsec_5cf9e1fab5b713c4e4e9179025e6fd704aa35f78ded7fddf202c22cd5f7f7ccd
order.service.url=http://localhost:8086
server.port=8090

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.group-id=payment-group
spring.kafka.consumer.auto-offset-reset=earliest